# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3e7043c54740f907b6b4ced27b3b39075027ada9831ae5a358af5665450c34cd05ef4b2822c8985b4781a7639e3989b4f596a4fcac91ab82add2b2477899e54

test:
  secret_key_base: a79de3d60266dcde50e59e8ce45a98feff3c83c5899c7958bf6b5dc11104c2f6d3b0be34b22623d95abcea8daafee9a88899921151d7ddfc0b065ce475259076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
